#' Bind and export multiple cohorts
#'
#' Reads per-cohort RDS files, binds them into a single data set, normalizes
#' special missing-value codes, filters out prefilled-but-empty rows, and
#' writes combined CSV/RDS/Excel exports.
#'
#' @param base_path Character scalar. Root directory containing the per-cohort
#'   RDS files \code{<cohort>.rds} previously created by
#'   \code{\link{read_cohort_xlsx}} (e.g. \code{"~/beki/data-raw/"}).
#' @param cohorts Character vector. Cohort identifiers (typically years such as
#'   \code{c("2017", "2018")}) used to construct the input RDS filenames
#'   \code{file.path(base_path, paste0(cohorts, ".rds"))}.
#' @param file_name_prefix Character scalar. Prefix used for the output
#'   filenames \code{<prefix>.rds}, \code{<prefix>.csv}, and
#'   \code{<prefix>.xlsx} written into \code{base_path}.
#' @param search_cols Character vector. Names of columns that are inspected to
#'   decide whether a row contains at least one non-missing “real” value.
#'
#' @return A named list with two tibbles: 
#'   \describe{
#'     \item{\code{all_cohorts}}{Row-bound union of all cohort tables, using the
#'       union of all columns and filling missing cells with \code{NA}.}
#'     \item{\code{all_values}}{Subset of \code{all_cohorts} restricted to rows
#'       where at least one of the key measurement/metadata columns contains a
#'       non-missing value.}
#'   }
#'
#' @details
#' This helper assumes that for each element of \code{cohorts} there exists a
#' corresponding RDS file \code{<cohort>.rds} in \code{base_path}, containing
#' a single tibble for that cohort. These files are typically generated by
#' \code{\link{read_cohort_xlsx}}.
#'
#' All character columns are first cleaned by converting the sentinel value
#' \code{"--wählen--"} and empty strings \code{""} to \code{NA}. The function
#' then keeps only those rows where at least one of a maximal set of
#' measurement and questionnaire variables (e.g. anthropometrics, sports
#' results, club membership) is non-missing, thereby removing purely
#' prefilled/blank rows.
#'
#' A timestamp column \code{Datensatz_erstellt_am} is added and set to the
#' current date via \code{Sys.Date()}.
#'
#' The function writes three snapshot files into \code{base_path}, using
#' \code{file_name_prefix} to construct the filenames:
#' \itemize{
#'   \item \code{<prefix>.rds}: Filtered data as an RDS file.
#'   \item \code{<prefix>.csv}: Filtered data as a CSV file (UTF-8).
#'   \item \code{<prefix>.xlsx}: Filtered data as an Excel workbook via
#'     \pkg{writexl}.
#' }
#'
#' @examples
#' \dontrun{
#' # Bind, clean, and export cohorts 2017 and 2018
#' res <- bind_cohorts(
#'   base_path        = "~/beki/data-raw/",
#'   cohorts          = c("2017", "2018"),
#'   file_name_prefix = "beki_scientific_use_file"
#' )
#'
#' res$all_cohorts  # raw union of all cohorts
#' res$all_values   # filtered rows with at least one real measurement
#' }
#'
#' @export
bind_cohorts <- function(base_path,
                         cohorts,
                         file_name_prefix = "beki_scientific_use_file", 
                         search_cols =  c(
    "Geschlecht", "Geburtsdatum_XLSX", "Geburtsdatum_Tag", "Geburtsdatum_Monat", "Geburtsdatum_Jahr",
    "Groesse_cm", "Masse_kg", "Schulsport_AG", "Vereinsmitglied",
    "Verein_1", "Verein_2", "Verein_3",
    "Verein_Woche",
    "S20_s", "BPT_m", "SLJ_cm", "OLB_s", "Star_s", "Run_m_1",
    "Run_54_m_Runden", "Run_Pylonen", "Run_m_2",
    "Anmerkungen")
    ) {
  # 1) RDS paths per cohort
  cohort_rds_paths <- file.path(base_path, paste0(cohorts, ".rds"))
  
  # 2) Read each cohort RDS (one tibble per cohort)
  cohort_tables <- purrr::map(cohort_rds_paths, readRDS)
  
  # 3) Bind rows across cohorts, keeping union of columns and filling missing with NA
  all_cohorts <- dplyr::bind_rows(cohort_tables)
  
  # 4) Normalize special missing codes ("--wählen--" and "")
  all_cohorts_clean <- all_cohorts %>%
    dplyr::mutate(dplyr::across(
      where(is.character),
      ~ ifelse(. %in% c("--wählen--", ""), NA, .)
    )) |>
    dplyr::mutate(Datensatz_erstellt_am = Sys.Date()) # Spalte "Datensatz_erstellt_am"
  
  # 5) Keep only rows where at least one of the relevant columns has data and sort columns alphabetically
  all_values <- all_cohorts_clean %>%
    dplyr::filter(dplyr::if_any(dplyr::any_of(search_cols), ~ !is.na(.)))

  # 6) Sort columns alphabetically
  all_values_alph <- all_values[ , order(names(all_values))]
  
  # 7) Save combined data (filtered)
  # saveRDS(all_cohorts,        file.path(base_path, "all_cohorts_raw.rds"))
  # readr::write_csv(all_cohorts, file.path(base_path, "all_cohorts_raw.csv"))
  
  saveRDS(all_values_alph,         file.path(base_path,paste0(file_name_prefix, ".rds")))
  readr::write_csv(all_values_alph, file.path(base_path,paste0(file_name_prefix, ".csv")))
  writexl::write_xlsx(all_values_alph, file.path(base_path,paste0(file_name_prefix, ".xlsx")))
  
  list(
    all_cohorts = all_cohorts,
    all_values  = all_values_alph
  )
}

#' Bind multiple Excel masks into one table
#'
#' Reads all \code{.xlsx} BeKiGeKi Excel masks in a directory (optionally
#' recursively), processes each file with \code{read_sheets_in_file()},
#' performs optional file-coverage checks, and optionally writes CSV/RDS
#' snapshot files.
#'
#' If \code{path_csv} or \code{path_rds} is non-NULL, the corresponding
#' snapshot is written.
#'
#' @param path_in Character. Directory containing \code{*.xlsx} Excel masks.
#' @param layout List. Layout specification for this cohort (as used
#'   by \code{read_sheets_in_file()}).
#' @param path_csv Character or NULL. Path to CSV snapshot file. If NULL,
#'   no CSV is written.
#' @param path_rds Character or NULL. Path to RDS snapshot file. If NULL,
#'   no RDS is written.
#' @param recursive Logical. If TRUE, search \code{path_in} recursively.
#' @param check_files Character. One of \code{"none"}, \code{"warn"},
#'   \code{"error"} to control the post-hoc check that all input files are
#'   represented in the data.
#'
#' @return A tibble with aggregated data from all files.
#' @export
#' @examples
#' \dontrun{
#' # Just bind, no snapshots
#' d <- bind_xlsx_files_in_dir(
#'   path_in  = "./in/",
#'   layout   = layout_2025
#' )
#'
#' # Bind and write CSV/RDS snapshots
#' d <- bind_xlsx_files_in_dir(
#'   path_in   = "./in/",
#'   layout    = layout_2025,
#'   path_csv  = "./tmp/bind_xlsx_files_in_dir.csv",
#'   path_rds  = "./tmp/bind_xlsx_files_in_dir.rds"
#' )
#' }
bind_xlsx_files_in_dir <- function(path_in  = "./tidy/",
                              layout,
                              path_csv = NULL,
                              path_rds = NULL,
                              recursive   = TRUE,
                              check_files = c("none", "warn", "error")) {
  check_files <- match.arg(check_files)

  file_names <- list.files(
    path       = path_in,
    pattern    = "^[^~].+\\.xlsx$",
    full.names = TRUE,
    recursive  = recursive
  )

  N <- length(file_names)
  if (N == 0L) {
    stop("No .xlsx files found in ", path_in)
  }

  dfs <- vector("list", N)
  for (n in seq_along(file_names)) {
    cat(sprintf("%d/%d files processed\n", n, N))
    dfs[[n]] <- read_sheets_in_file(
      file   = file_names[n],
      layout = layout
    )
  }

  d <- dplyr::bind_rows(dfs)

  check_files_covered(file_names, d, file_col = "XLSX_Dateiname",
                      mode = check_files)

  if (!is.null(path_csv)) {
    dir.create(dirname(path_csv), showWarnings = FALSE, recursive = TRUE)
    utils::write.csv(d, file = path_csv, row.names = FALSE)
  }
  if (!is.null(path_rds)) {
    dir.create(dirname(path_rds), showWarnings = FALSE, recursive = TRUE)
    saveRDS(d, file = path_rds)
  }

  d
}

