#' Bind and export multiple cohorts
#'
#' Reads per-cohort RDS files, binds them into a single data set, normalizes
#' special missing-value codes, filters out prefilled-but-empty rows, and
#' writes combined CSV/RDS/Excel exports.
#'
#' @param base_path Character scalar. Root directory containing the per-cohort
#'   RDS files \code{<cohort>.rds} previously created by
#'   \code{\link{read_cohort_xlsx}} (e.g. \code{"~/beki/data-raw/"}).
#' @param cohorts Character vector. Cohort identifiers (typically years such as
#'   \code{c("2017", "2018")}) used to construct the input RDS filenames
#'   \code{file.path(base_path, paste0(cohorts, ".rds"))}.
#'
#' @return A named list with two tibbles:
#' \describe{
#'   \item{\code{all_cohorts}}{Row-bound union of all cohort tables, using the
#'     union of all columns and filling missing cells with \code{NA}.}
#'   \item{\code{all_values}}{Subset of \code{all_cohorts} restricted to rows
#'     where at least one of the key measurement/metadata columns contains a
#'     non-missing value.}
#' }
#'
#' @details
#' This helper assumes that for each element of \code{cohorts} there exists a
#' corresponding RDS file \code{<cohort>.rds} in \code{base_path}, containing
#' a single tibble for that cohort. These files are typically generated by
#' \code{\link{read_cohort_xlsx}}.
#'
#' All character columns are first cleaned by converting the sentinel value
#' \code{"--wählen--"} and empty strings \code{""} to \code{NA}. The function
#' then keeps only those rows where at least one of a maximal set of
#' measurement and questionnaire variables (e.g. anthropometrics, sports
#' results, club membership) is non-missing, thereby removing purely
#' prefilled/blank rows.
#'
#' The function writes four snapshot files into \code{base_path}:
#' \itemize{
#'   \item \code{all_cohorts_raw.rds}, \code{all_cohorts_raw.csv}:
#'     full bound data across cohorts before row filtering.
#'   \item \code{all_cohorts_filtered.rds}, \code{all_cohorts_filtered.csv}:
#'     filtered data with only rows containing at least one real value in the
#'     key columns.
#' }
#' It also writes an Excel export \code{all_cohorts_filtered.xlsx} using
#' \pkg{writexl}.
#'
#' @examples
#' \dontrun{
#' # Bind, clean, and export cohorts 2017 and 2018
#' res <- bind_cohorts(
#'   base_path = "~/beki/data-raw/",
#'   cohorts   = c("2017", "2018")
#' )
#'
#' res$all_cohorts  # raw union of all cohorts
#' res$all_values   # filtered rows with at least one real measurement
#' }
#'
#' @export
bind_cohorts <- function(base_path, cohorts,
                         search_cols =  c(
    "Geschlecht", "Geburtsdatum_XLSX", "Geburtsdatum_Tag", "Geburtsdatum_Monat", "Geburtsdatum_Jahr",
    "Groesse_cm", "Masse_kg", "Schulsport_AG", "Vereinsmitglied",
    "Verein_1", "Verein_2", "Verein_3",
    "Verein_Woche",
    "S20_s", "BPT_m", "SLJ_cm", "OLB_s", "Star_s", "Run_m1",
    "Run_54_m_Runden", "Run_Pylonen", "Run_m2",
    "Anmerkungen")
    ) {
  # 1) RDS paths per cohort
  cohort_rds_paths <- file.path(base_path, paste0(cohorts, ".rds"))
  
  # 2) Read each cohort RDS (one tibble per cohort)
  cohort_tables <- purrr::map(cohort_rds_paths, readRDS)
  
  # 3) Bind rows across cohorts, keeping union of columns and filling missing with NA
  all_cohorts <- dplyr::bind_rows(cohort_tables)
  
  # 4) Normalize special missing codes ("--wählen--" and "")
  all_cohorts_clean <- all_cohorts %>%
    dplyr::mutate(dplyr::across(
      where(is.character),
      ~ ifelse(. %in% c("--wählen--", ""), NA, .)
    ))
  
  # 5) Keep only rows where at least one of the relevant columns has data  
  all_values <- all_cohorts_clean %>%
    dplyr::filter(dplyr::if_any(dplyr::any_of(search_cols), ~ !is.na(.)))

  
  # 6) Save combined data (full and filtered)
saveRDS(all_cohorts,        file.path(base_path, "all_cohorts_raw.rds"))
  readr::write_csv(all_cohorts, file.path(base_path, "all_cohorts_raw.csv"))
  
  
  saveRDS(all_values,         file.path(base_path, "all_cohorts.rds"))
  readr::write_csv(all_values, file.path(base_path, "all_cohorts.csv"))
  writexl::write_xlsx(all_values, file.path(base_path, "all_cohorts.xlsx"))
  
  list(
    all_cohorts = all_cohorts,
    all_values  = all_values
  )
}
